# Generated by Django 5.2.11 on 2026-02-09 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_fa', models.CharField(max_length=100, verbose_name='Name (Farsi)')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('change_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('volume', models.BigIntegerField(default=0)),
                ('market_cap', models.BigIntegerField(default=0)),
                ('high_24h', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('low_24h', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('open_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sector', models.CharField(max_length=50)),
                ('sector_fa', models.CharField(max_length=50, verbose_name='Sector (Farsi)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stock_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stocks.stock')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'ordering': ['-timestamp'],
                'unique_together': {('stock', 'timestamp')},
            },
        ),
    ]
