# Generated by Django 5.2.11 on 2026-02-09 13:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('title_fa', models.CharField(max_length=200, verbose_name='Title (Farsi)')),
                ('message', models.TextField()),
                ('message_fa', models.TextField(verbose_name='Message (Farsi)')),
                ('type', models.CharField(choices=[('order_matched', 'Order Matched'), ('order_cancelled', 'Order Cancelled'), ('price_alert', 'Price Alert'), ('system', 'System'), ('transaction', 'Transaction')], max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
